import { Video } from './types';

export const MOCK_VIDEOS: Video[] = [
  {
    id: '1',
    title: 'Modern Web Development in 2024',
    thumbnail: 'https://picsum.photos/seed/webdev/800/450',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    channelName: 'TechAcademy',
    channelAvatar: 'https://picsum.photos/seed/tech/100/100',
    views: '1.2M',
    postedAt: '2 days ago',
    duration: '12:45',
    description: 'Explore the latest trends in web development, from React 19 to advanced CSS techniques.',
    category: 'Technology',
    likes: 45000,
    subscribers: '850K'
  },
  {
    id: '2',
    title: 'Top 10 Travel Destinations in Asia',
    thumbnail: 'https://picsum.photos/seed/travel/800/450',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    channelName: 'Wanderlust',
    channelAvatar: 'https://picsum.photos/seed/wander/100/100',
    views: '850K',
    postedAt: '1 week ago',
    duration: '15:20',
    description: 'Join us as we explore the most beautiful and hidden gems across Asia.',
    category: 'Travel',
    likes: 32000,
    subscribers: '1.2M'
  },
  {
    id: '3',
    title: 'Mastering the Art of Italian Cooking',
    thumbnail: 'https://picsum.photos/seed/cooking/800/450',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    channelName: 'ChefSecrets',
    channelAvatar: 'https://picsum.photos/seed/chef/100/100',
    views: '2.5M',
    postedAt: '1 month ago',
    duration: '22:10',
    description: 'Learn how to make authentic pasta and pizza from scratch with professional tips.',
    category: 'Food',
    likes: 120000,
    subscribers: '3.4M'
  },
  {
    id: '4',
    title: 'The Future of Artificial Intelligence',
    thumbnail: 'https://picsum.photos/seed/ai/800/450',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    channelName: 'FutureTech',
    channelAvatar: 'https://picsum.photos/seed/future/100/100',
    views: '500K',
    postedAt: '5 hours ago',
    duration: '10:30',
    description: 'How AI is changing the world and what to expect in the next decade.',
    category: 'Technology',
    likes: 15000,
    subscribers: '200K'
  },
  {
    id: '5',
    title: 'Morning Yoga Routine for Beginners',
    thumbnail: 'https://picsum.photos/seed/yoga/800/450',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    channelName: 'HealthyLife',
    channelAvatar: 'https://picsum.photos/seed/health/100/100',
    views: '3.1M',
    postedAt: '3 months ago',
    duration: '18:00',
    description: 'Start your day with energy and focus with this simple 18-minute yoga flow.',
    category: 'Health',
    likes: 210000,
    subscribers: '5.1M'
  },
  {
    id: '6',
    title: 'Epic Mountain Biking in the Alps',
    thumbnail: 'https://picsum.photos/seed/bike/800/450',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    channelName: 'ExtremeSports',
    channelAvatar: 'https://picsum.photos/seed/extreme/100/100',
    views: '150K',
    postedAt: '1 day ago',
    duration: '08:45',
    description: 'Breathtaking views and heart-pounding descents in the heart of the Alps.',
    category: 'Sports',
    likes: 8000,
    subscribers: '45K'
  }
];

export const MOCK_SHORTS: Video[] = [
  {
    id: 's1',
    title: 'Amazing Magic Trick Revealed! 🎩✨',
    thumbnail: 'https://picsum.photos/seed/magic/400/700',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    channelName: 'MagicMoments',
    channelAvatar: 'https://picsum.photos/seed/magic/100/100',
    views: '2.4M',
    postedAt: '1 day ago',
    duration: '0:59',
    description: 'You won\'t believe how this is done!',
    category: 'Entertainment',
    likes: 340000,
    subscribers: '1.2M'
  },
  {
    id: 's2',
    title: 'Quick & Easy Breakfast Recipe 🍳',
    thumbnail: 'https://picsum.photos/seed/breakfast/400/700',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    channelName: 'ChefSecrets',
    channelAvatar: 'https://picsum.photos/seed/chef/100/100',
    views: '850K',
    postedAt: '3 hours ago',
    duration: '0:45',
    description: 'Make this in under 5 minutes!',
    category: 'Food',
    likes: 120000,
    subscribers: '3.4M'
  },
  {
    id: 's3',
    title: 'Cute Puppy Learning to Walk 🐶❤️',
    thumbnail: 'https://picsum.photos/seed/puppy/400/700',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    channelName: 'PetLovers',
    channelAvatar: 'https://picsum.photos/seed/pets/100/100',
    views: '5.1M',
    postedAt: '2 days ago',
    duration: '0:30',
    description: 'The most adorable thing you will see today.',
    category: 'Pets',
    likes: 890000,
    subscribers: '2.1M'
  },
  {
    id: 's4',
    title: 'Insane Skateboard Trick 🛹🔥',
    thumbnail: 'https://picsum.photos/seed/skate/400/700',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    channelName: 'ExtremeSports',
    channelAvatar: 'https://picsum.photos/seed/extreme/100/100',
    views: '1.2M',
    postedAt: '5 hours ago',
    duration: '0:40',
    description: 'First time landing this trick!',
    category: 'Sports',
    likes: 150000,
    subscribers: '45K'
  },
  {
    id: 's5',
    title: 'Tech Gadgets You Need in 2024 📱',
    thumbnail: 'https://picsum.photos/seed/gadgets/400/700',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    channelName: 'TechAcademy',
    channelAvatar: 'https://picsum.photos/seed/tech/100/100',
    views: '3.3M',
    postedAt: '1 week ago',
    duration: '0:55',
    description: 'Must-have tech for your setup.',
    category: 'Technology',
    likes: 420000,
    subscribers: '850K'
  }
];
